version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      #MYSQL_USER: $DB_USER
      #MYSQL_PASSWORD: $DB_PASS
    ports:
      - "3306:3306"
    volumes:
      - ./database/db_data:/var/lib/mysql
  web:
    image: nap6/serious-game
    container_name: web_app
    env_file: .env
    environment:
      DB_HOST: db
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
    ports:
      - "80:3000"